### ISSUE TITLE
Installed all python 3.6.0 modules, but having problem.

### ISSUE THREAD

**Issue by refriedfood** [freiheit/discord_feedbot#189]
```
C:\discord_feedbot-main>python36 feed2discord.py
Traceback (most recent call last):
  File "feed2discord.py", line 12, in <module>
    import aiomysql
  File "D:\Utilities\Python\Python36\lib\site-packages\aiomysql\__init__.py", line 32, in <module>
    from .connection import Connection, connect
  File "D:\Utilities\Python\Python36\lib\site-packages\aiomysql\connection.py", line 19, in <module>
    from pymysql.util import byte2int, int2byte
ModuleNotFoundError: No module named 'pymysql.util'
^error

C:\discord_feedbot-main>python36 show_all_entries.py
Give me 1 feed URL on the command-line, and I'll give the first entry from it.
^ works

C:\discord_feedbot-main>python36 feedsearch.py
Traceback (most recent call last):
  File "feedsearch.py", line 6, in <module>
    from feedsearch_crawler import search
ModuleNotFoundError: No module named 'feedsearch_crawler'
^error
```

Any help would be appreciated.

**Comment by freiheit** [comment]
I forgot to add feedsearch_crawler to requirements.txt, because it's part of one of the tools and not of the core program. This is fixed in the main branch now.

It looks like something went wrong with your aiomysql install? How did you install that? Something with "pip -r requirements.txt", or some other way? You may need to install some system libraries for mysql stuff ("libmysqlclient-dev", "mysql-devel", "libmariadb-dev",  "mariadb-devel" or something like that).

If you're using sqlite (the default), you can just comment out the aiomysql line, too.

**Comment by refriedfood** [comment]
I installed everything from python -m pip install -r requirements.txt, however, I received this error after the original configuration:
```
/discord_feedbot/./feed2discord.py", line 214, in <module>
    client = discord.Client(
TypeError: Client.__init__() missing 1 required keyword-only argument: 'intents'
```
Therefore, I hunted down the possible cause of that and installed discord 1.7.3 with `-m pip install -U discord==1.7.3 pip install -U discord.py==1.7.3` to the now received error I originally posted. I have not been able to get past it, and I've tried multiple version of python: 3.6-3.10 on both windows and ubuntu with no luck. I'm at a loss, and any help would be appreciated.

Also, does this require uvloop? As that isn't supported on windows.

**Comment by freiheit** [comment]
> I installed everything from python -m pip install -r requirements.txt, however, I received this error after the original configuration:
> 
> ```
> /discord_feedbot/./feed2discord.py", line 214, in <module>
>     client = discord.Client(
> TypeError: Client.__init__() missing 1 required keyword-only argument: 'intents'
> ```
>
> Therefore, I hunted down the possible cause of that and installed discord 1.7.3 with `-m pip install -U discord==1.7.3 pip install -U discord.py==1.7.3` to the now received error I originally posted. I have not been able to get past it, and I've tried multiple version of python: 3.6-3.10 on both windows and ubuntu with no luck. I'm at a loss, and any help would be appreciated.

Looks like I need to lock the discord version more specifically, and/or update my code to pass that intents param...

> Also, does this require uvloop? As that isn't supported on windows.

Not unless one of the dependencies requires it. The individual asyncio "threads" spend most of their time sleeping, so I doubt uvloop would be worth the downside of not working on Windows.

**Comment by freiheit** [comment]
I just realized: You're using python 3.6, but I believe the oldest python that will work is Python 3.8. I run it with Python 3.9, so it's possible something requiring python 3.9+ snuck in at some point.

Try it with a newer python. Any of 3.8.16, 3.9.16, 3.10.9 or 3.11.1 should be fine.

https://github.com/freiheit/discord_feedbot/blob/main/INSTALLING.md#requirements
