### ISSUE TITLE
Edit titles (or other fields) with regular expression (or similar)

### ISSUE THREAD

**Issue by DMann420** [freiheit/discord_feedbot#35]
As per our discussion, it would be a good feature to be able to modify the contents of a title or description for a feed. 

Example:
Original Title: `#IceHockey #Livescore @ScoresPro: (SUI-) #ZSC Lions vs #SC Bern: 2-1
E/p2`

New Title: `@ScoresPro: (SUI-) #ZSC Lions vs #SC Bern: 2-1
End of Period 2`

**Comment by freiheit** [comment]
I think this could be done with a paired regex type thing, to get a sort of sed-like feature, so that something like 

```
search=#IceHockey #Livescore
replace=
```

would turn into
```
s/#IceHockey #Livescore//g
```

But I have to think about this... Probably revisit this much later.
