### ISSUE TITLE
Asyncio Issue

### ISSUE THREAD

**Issue by synzen** [freiheit/discord_feedbot#36]
This problem is most likely the exact same problem as stated here https://github.com/freiheit/discord_feedbot/issues/18

The bot would be able to send feeds for a maybe a few min before the scirpt just halts, and won't do anything until I press any key which seems to cause the bot to formally stop.

Here is a some data: http://pastebin.com/CzzxNbur
This is with log=1. Right after the first `DEBUG:__main__:warframe:sleeping for 60 seconds` (line 5) nothing happened for maybe an hour until I pressed a key, then the rest of the log there showed up and stopped the bot

Here is with log=3 http://pastebin.com/8k7BTJDr

I am running Windows 10 Pro x64

**Comment by freiheit** [comment]
I'm having trouble figuring out what is going on here...

Looks like it's a problem when talking to Discord, not a problem with handling anything in the feed itself...  What version of the discord api do you have installed?

**Comment by mtan9946** [comment]
I'm not sure how to check the discord api version but these are the python packages I have installed 
![image](https://cloud.githubusercontent.com/assets/18688793/19825053/ceb56350-9d42-11e6-97e2-d2f9056e868c.png)

I assumed that installing the latest discord.py would be enough
