### ISSUE TITLE
Unable to run 'invalid syntax'

### ISSUE THREAD

**Issue by nEo-1664** [freiheit/discord_feedbot#37]
When trying to run this in Ubuntu 16.04 server, I get the following error;

  File "feed2discord.py", line 311
    yield from client.send_typing(channel['object'])
             ^
Any thoughts? I can't see anything else about it.

**Comment by freiheit** [comment]
Are you running it with python less than 3.4? Python 3.4 or newer is required.

**Comment by nEo-1664** [comment]
Sorted. Now another issue, but that's in a new issue.
