### ISSUE TITLE
Game status

### ISSUE THREAD

**Issue by KongGal** [freiheit/discord_feedbot#45]
Is there anyway to disable the game status of the bot so it doesn't takeover the status?

**Comment by freiheit** [comment]
In feed2discord.py, you can remove this line:
```python
 yield from client.change_presence(game=discord.Game(name=gameplayed),status=discord.Status.idle)
```

I'll make that configurable, but just haven't gotten around to it.

**Comment by KongGal** [comment]
Thanks
