### ISSUE TITLE
Wrapping fieldname with ``` tags makes the bot ignore the field

### ISSUE THREAD

**Issue by Bewinxed** [freiheit/discord_feedbot#52]
Hello, I got the bot up and running, however, in my local config my feed is like this

`fields = "New Post",link,**title**,```description```,".."`

When i wrap the description with ``` it gets ignored, what i want is to wrap the content inside of the description within a code block, so it looks tidier, am i doing something wrong or is there another way?

**Comment by freiheit** [comment]
Had a bug in handling those. Should be fixed in aa8da4c, so pull latest master and try that.
