### ISSUE TITLE
ResourceWarning: unclosed transport 

### ISSUE THREAD

**Issue by cod3dump** [freiheit/discord_feedbot#59]
I am not able to get the bot running. Getting the error messages below. I'd appreciate your help in understanding what went wrong.

D:\discord_feedbot-master>feed2discord.py
C:\Python35\lib\asyncio\selector_events.py:581: ResourceWarning: unclosed transport <_SelectorSocketTransport fd=716>
  warnings.warn("unclosed transport %r" % self, ResourceWarning)
C:\Python35\lib\site-packages\aiohttp\client.py:88: ResourceWarning: Unclosed client session <aiohttp.client.ClientSession object at 0x03F79930>
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x03F79930>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<background_check_feed() running at D:\discord_feedbot-master\feed2discord.py:402> wait_for=<Future pending cb=[Task._wakeup()]>>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<background_check_feed() running at D:\discord_feedbot-master\feed2discord.py:402> wait_for=<Future pending cb=[Task._wakeup()]>>
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<background_check_feed() running at D:\discord_feedbot-master\feed2discord.py:402> wait_for=<Future pending cb=[Task._wakeup()]>>

**Comment by freiheit** [comment]
I can't reproduce this on my setup. This is usually a problem with DNS, SSL certificates, time sync or network connectivity. Make sure "wget" can talk to discordapp.com.
