### ISSUE TITLE
Request to add bot

### ISSUE THREAD

**Issue by tarragon** [freiheit/discord_feedbot#61]
Server: Spaceman's Retreat.
Contact: zzUrbanSpaceman#7994 on Discord is probably best, or via Github. I'd rather not put an email address that will be scraped and spammed in an issue.
Room ID: 321060041345990656

Thanks!

**Comment by freiheit** [comment]
This is now setup with a reasonable default set of feeds.

**Comment by tarragon** [comment]
Unfortunately this does not appear to be working - I saw an update in the feed room in the community devs discord, but I've had nothing appear in my own. It could also just be a quiet period but it seems the one in the community devs discord has got a lot quieter too.
