### ISSUE TITLE
Request for Bot Adding

### ISSUE THREAD

**Issue by danrockliff** [freiheit/discord_feedbot#62]
Discord Server ID:347709902715748353
Discord Server Name: EXO  Enforcers
Room ID for newsfeed: 398400813090865152
My DiscordID: @Rockswift#3124 

Newsfeed: Would be great to get Elite Dangerous Community Goal Weekly information sent to this channel.

**Comment by freiheit** [comment]
I set this up with galnet (since that includes CG info), the EliteCG reddit and the EliteCG FDev forum.

**Comment by danrockliff** [comment]
Brilliant, thank you

Regards Daniel

On 11 Mar 2018, at 23:55, Eric Eisenhart <notifications@github.com<mailto:notifications@github.com>> wrote:


I set this up with galnet (since that includes CG info), the EliteCG reddit and the EliteCG FDev forum.
