### ISSUE TITLE
Requesting Discord Access

### ISSUE THREAD

**Issue by daPhantom** [freiheit/discord_feedbot#65]
Hey there :-)

We're a small group of buddies and are running a game related discord server including an elite channel. We would love to have posted the newest elite related news in that channel.

Server name: Grenzdebile Randgruppe
Server id: 341544400360570880
Channel id: 341566368870563842
Contact: Information in my Github profile ;)

Thank you very much! :)

**Comment by freiheit** [comment]
Ok, this is set up with all the feeds that are "news" type things, including galnet.

**Comment by daPhantom** [comment]
Thanks!
