### ISSUE TITLE
Requesting access

### ISSUE THREAD

**Issue by DRGrandreefer** [freiheit/discord_feedbot#71]
Channel ID: 423587262136057857
I would be interested in galnet news, FDev forums CG info, Elite Dangerous newsletter, Elite Dangerous patch notes, Elite Dangerous dev updates, and the Elite Dangerous News and updates. Thank you so much

**Comment by freiheit** [comment]
What's the name of this discord server?

**Comment by DRGrandreefer** [comment]
Yeah I guess that would help. Duh. DRInc. Discord.

**Comment by freiheit** [comment]
Ok, this is set up now
