### ISSUE TITLE
i would like to get your bot on my server. 

### ISSUE THREAD

**Issue by lunchpaddle** [freiheit/discord_feedbot#72]
pls contact me at rivalvapes@gmail.com 

the channel name is HIVE 

the webhook for the channel we would like to use is: 
https://discordapp.com/api/webhooks/424071296704446468/cHErls51TKuLIc8sHt3d7o0zO4M_CurKhdz8bD_Kz4g6mrOzdZX2L_wNdahhmOiJaNeJ

im not sure what information you need from me to get this done haha :) hope to hear back soon!

**Comment by freiheit** [comment]
What's the name of the discord server itself?

I need the channel ID, not a webhook.
