### ISSUE TITLE
New feedbot user 

### ISSUE THREAD

**Issue by RtGearz** [freiheit/discord_feedbot#75]
Discord: R/t's
contack: Cmdr R/t #8306
               rtgearz@gmail.com
feed-news-room, 435181036427673601
  galnet news
  Elite Dangerous patch notes
  FDev forums Cg
  Elite Dangerous newslettters
  /r/EliteCG
  /r/EliteOne
feed-content, 435202974785077249
  Hutton Orbital Podcast
  Lave Radio Podcast
  Nice E:D blog

**Comment by freiheit** [comment]
This is set up
