### ISSUE TITLE
New Feedbot User

### ISSUE THREAD

**Issue by IAmBob224** [freiheit/discord_feedbot#76]
Discord Server: UToS (United Technocracy of Systems)
Discord Username: IAmBob224#1803
galnet: 375084913155768320
-galnet news

elite-information: 447158973527883777
FDev forums CG info
-Elite Dangerous newsletters
-Elite Dangerous patch notes
-Elite Dangerous dev updates
-Elite Dangerous News and Updates
(I don't know if the 4th addition will create double posts with the first 3, but if it also includes more and all the information of the previous 3, just use the 4th one)

Thanks for all the help 👍

**Comment by freiheit** [comment]
I think this is all set up now.
