### ISSUE TITLE
Feedbot Request for Discord Channel

### ISSUE THREAD

**Issue by PaleGringo** [freiheit/discord_feedbot#77]
The name of your discord server: PaleGringo (ID 468811725840318464)
Contact info to reach you: @PaleGringo (Twitter DM), PaleGringo#6898 (Discord)
The id number for your room: 469764789950742538
The feeds you want: Elite Dangerous GalNet News

Thanks in advance, and please let me know where I can shoot over a donation for your time and efforts.

**Comment by freiheit** [comment]
I think this is set up now. Nothing will show up until the next galnet news update.

No donation needed, but if you insist, either: https://beerpay.io/freiheit/discord_feedbot or a donation in my name (Eric Eisenhart) to EFF, ACLU, Planned Parenthood or Sonoma County Bicycle Coalition.
