### ISSUE TITLE
AttributeError: 'Client' object has no attribute 'async_event'

### ISSUE THREAD

**Issue by vascocosta** [freiheit/discord_feedbot#88]
I'm running pretty recent versions of discord.py(1.23) and aiohttp(3.5.4) yet the bot won't run, complaining with the following strack trace:

./feed2discord.py
gluon@helium:~/var/discord/bots/discord_feedbot$ ./feed2discord.py
gluon@helium:~/var/discord/bots/discord_feedbot$ ./feed2discord.py
./feed2discord.py:181: DeprecationWarning: The object should be created from async function
  httpclient = aiohttp.ClientSession()
/home/gluon/.local/lib/python3.5/site-packages/aiohttp/connector.py:730: DeprecationWarning: The object should be created from async function
  loop=loop)
/home/gluon/.local/lib/python3.5/site-packages/aiohttp/connector.py:735: DeprecationWarning: The object should be created from async function
  resolver = DefaultResolver(loop=self._loop)
/home/gluon/.local/lib/python3.5/site-packages/aiohttp/cookiejar.py:55: DeprecationWarning: The object should be created from async function
  super().__init__(loop=loop)
WARNING:discord.client:PyNaCl is not installed, voice will NOT be supported
Traceback (most recent call last):
  File "./feed2discord.py", line 757, in <module>
    @client.async_event
AttributeError: 'Client' object has no attribute 'async_event'
/home/gluon/.local/lib/python3.5/site-packages/aiohttp/client.py:300: ResourceWarning: Unclosed client session <aiohttp.client.ClientSession object
 at 0x7f7ad652bb70>

**Comment by freiheit** [comment]
Couldn't reproduce, and code (and libraries used) have all changed a lot since then
